### ISSUE TITLE
Generate schema for API Gateway responses

### ISSUE THREAD

**Issue by esmarkowski** [rubyonjets/jets#620]
## Summary

Add Model definition to schema when building API Gateway templates. Optionally, allow JSON schema to be defined for each endpoint. 

## Motivation

When schema is defined in API Gateway it's possible to use the SDK to generate API clients directly from AWS. Without the schema the SDK is a useless pile of garbage.  

## Reference-level explanation

When using models in Jets, we should have enough information to create `AWS::ApiGateway::Model`. When building the CFN templates for API Gateway we could add the appropriate definition. 

```yaml
Type: AWS::ApiGateway::Model
Properties: 
  ContentType: String
  Description: String
  Name: String
  RestApiId: String
  Schema: Json
```

I'm going to take a stab at implementing this, but wanted to stub out a feature for reference.
