### ISSUE TITLE
Feature Request: Support Timezones in cloudwatch triggers

### ISSUE THREAD

**Issue by onnimonni** [rubyonjets/jets#64]
I think timezones are not currently possible because the cron support in AWS cloudwatch is really limited.

It would be nice to have a feature in Jets which understands different timezones and converts them into multiple different UTC cron definitions.

Here's an example from [serverless plugin](https://github.com/UnitedIncome/serverless-local-schedule) which converts this config:
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          timezone: America/New_York
```
To effectively do the same thing as this one
```yaml
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 15 * 1-2,12 ? *) # full non-DST months
      - schedule:
          rate: cron(0 15 1-10 3 ? *) # non-DST portion of March
      - schedule:
          rate: cron(0 14 11-31 3 ? *) # DST portion of March
      - schedule:
          rate: cron(0 14 * 4-10 ? *) # full DST months
      - schedule:
          rate: cron(0 14 1-3 11 ? *) # DST portion of November
      - schedule:
          rate: cron(0 15 4-31 11 ? *) # non-DST portion of November
```

This would make Jets even more user friendly for configuring jobs.
