### ISSUE TITLE
Missing API Methods leads to 500 errors

### ISSUE THREAD

**Issue by SteffanPerry** [rubyonjets/jets#705]
I am not 100% sure if this is an config issue on my side.

## Checklist

- [ 👍 ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [👍  ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |OSX 14.0 |
| Jets             | 5.0.8|
| Ruby             | 3.2.2|

---

## Expected Behaviour
Routes map to controller lambda via lambda proxy

## Current Behavior
I have created a brand new jets project on 5.0.8. I have a few different controller methods using GET/PUT/POST,etc. When deploying, only a get catachall seems to be created on API gateway

## Step-by-step reproduction instructions
Create a clean jets 5.0.8 project, add a model and crud methods, deploy.

## Code Sample
Output from jets routes:
```
+--------------------+---------+-------------------------------------+--------------------------+
|    As (Prefix)     |  Verb   |         Path (URI Pattern)          |    Controller#action     |
+--------------------+---------+-------------------------------------+--------------------------+
| health             | GET     | /health                             | health#health            |
| v1_sources         | GET     | /v1/sources                         | v1/sources#index         |
| v1_sources         | POST    | /v1/sources                         | v1/sources#create        |
| v1_source          | GET     | /v1/sources/:id                     | v1/sources#show          |
| v1_source          | PUT     | /v1/sources/:id                     | v1/sources#update        |
| v1_source          | PATCH   | /v1/sources/:id                     | v1/sources#update        |
| v1_source_channels | GET     | /v1/sources/:source_id/channels     | v1/channels#index        |
| v1_source_channels | POST    | /v1/sources/:source_id/channels     | v1/channels#create       |
| v1_source_channel  | GET     | /v1/sources/:source_id/channels/:id | v1/channels#show         |
| v1_source_channel  | PUT     | /v1/sources/:source_id/channels/:id | v1/channels#update       |
| v1_source_channel  | PATCH   | /v1/sources/:source_id/channels/:id | v1/channels#update       |
| v1_account_sources | GET     | /v1/account_sources                 | v1/account_sources#index |
| v1_account_source  | GET     | /v1/account_sources/:id             | v1/account_sources#show  |
| v1_insights        | GET     | /v1/insights                        | v1/insights#index        |
|                    | OPTIONS | /*catchall                          | cors#preflight           |
+--------------------+---------+-------------------------------------+--------------------------+
```

API Gateway Resources:
```
/
  GET
  /{+catchall}
```

ApiMethod template:
```
Resources:
  AnyCatchallApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId: !Ref CatchallApiResource
      RestApiId: !Ref RestApi
      HttpMethod: GET
      RequestParameters: {}
      AuthorizationType: NONE
      ApiKeyRequired: 'false'
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JetsControllerLambdaFunction}/invocations
      MethodResponses: []
Parameters:
  RestApi:
    Type: String
  JetsControllerLambdaFunction:
    Type: String
  CatchallApiResource:
    Type: String
```
